<<dd_version: 2>>
<<dd_include: header.txt>>

```
<<dd_do: quietly>>
set linesize 96
<</dd_do>>
```

# RDM 2024 - Data cleaning for analysis - Practical report

* Date: <<dd_display: "`1'">>
* Author: <<dd_display: "`2'">>

## Practical instructions

Upload to your GitHub repository by Monday, April 22nd 2024.

### Material

* Three uncleaned datasets from a Malaria Indicator Survey in Papua New Guinea (PNG). Modified from 2019/20 MIS by PNGIMR.
  * practical_household.dta
  * practical_individual.dta
  * practical_village.csv
* Copies of forms (in Word)
  * MIS2020 FORM 2.doc
  * MIS2020 FORM 3.doc
* A variable list in Excel
  * variable-list-RDM2023.xlsx
* Table shells
  * RDM_MIS_tabulations.xlsx

### Data cleaning exercise

* identify errors in individual variables in each dataset
* clean the datasets 
* merge the datasets for analyses: village and household info to individual obs.
* document all procedures in an annotated Stata do-file
* generate a codebook 

### Analysis exercise

* Completed Tables 1-4
* Basic Codebook
* Answer to research questions, supported by a table or graph, neatly presented in a Word document

### Version control exercise

* Version-controlled do-files (commit all steps with informative messages)

## About the National Malaria Indicator Survey 2019/2020

Cross-sectional household survey in all 22 provinces of Papua New Guinea.

* 5 randomly sampled villages/province
* ca. 30 random households/village
* Structured interviews
* Finger-prick blood sample for malaria diagnosis by Rapid Diagnostic Test (RDT) and light microscopy

## Data exploration and cleaning

### Dataset 1: household-level data

This dataset is stored in **practical_household.dta**.

```
<<dd_do>>
do clean_household.do
<</dd_do>>
```

```
<<dd_do>>
graph hbar mosquitonet, over(province)
<</dd_do>>
```

<<dd_graph: sav("../rdm2024_results/figure1.png") replace>>


### Dataset 2: individual-level data

This dataset is stored in **practical_individual.dta**.

```
<<dd_do>>
do clean_individual.do
<</dd_do>>
```

### Dataset 3: survey village data

This dataset is stored in **practical_village.csv**.

```
<<dd_do>>
do clean_village.do
<</dd_do>>
```

### Merge

```
<<dd_do>>
do merge.do
<</dd_do>>
```

### Codebook

```
<<dd_do>>
do codebook.do
<</dd_do>>
```

## Questions

Answer the following questions, supported by a table or graph and provide relevant descriptive values.

### Implementation question: How many household interviews were conducted per month?

### Research question 1: Are members of households that own at least one long-lasting insecticidal net (LLIN) less likely to be infected with malaria parasites?

### Research question 2: Does prevalence of Plasmodium vivax and P. falciparum differ between altitudinal zones?

Which provinces have the highest prevalence of Plasmodium vivax infections in children <5 years of age?

### Bonus research question: What is the sensitivity and specificity of RDTs compared to microscopy (any species)?